Add connectionFactory getter
spring-cloud/spring-cloud-stream-binder-rabbit pull request #359
Opened 2022-03-29 14:32 UTC by tzolov

Resolves #358

2022-03-29 14:40 UTC, garyrussell requested changes
I suggest we backport this to 3.2.x as well.

2022-03-29 14:40 UTC, garyrussell commented on spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java
> +	public ConnectionFactory getConnectionFactory() {
Javadocs?

2022-03-29 15:01 UTC, tzolov commented on spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java
> +	public ConnectionFactory getConnectionFactory() {
addressed

2022-03-29 15:10 UTC, garyrussell approved these changes

2022-03-29 15:33 UTC, sobychacko commented
@tzolov Any chance, you can issue this PR against the core repository? https://github.com/spring-cloud/spring-cloud-stream. Rabbit binder is now part of the mono-repo structure (for `main` and `3.2.x`).

2022-03-30 13:20 UTC, tzolov commented
@sobychacko here it is https://github.com/spring-cloud/spring-cloud-stream/pull/2315

2022-03-30 15:59 UTC, closed without merging